development: 
  cloud_name: "dh6pbcoj9"
  api_key: "614871444358641"
  api_secret: "Em2WzF1-fQ07GIux4X2Txn6-wSk"
  secure: true

production: 
  cloud_name: "dh6pbcoj9"
  api_key: "614871444358641"
  api_secret: "Em2WzF1-fQ07GIux4X2Txn6-wSk"
  secure: true


  